/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testRollMethod() {
        Library libraryForTest = new Library();
        int[] expected = new int[4];
        assertTrue("The method should return an array with the same length of the input number ", libraryForTest.roll(4).length == expected.length);
    }

    @Test public void testContainedDuplicatesMethod(){
        Library libraryForTest = new Library();
        int[] noDupes = new int[] {2, 3, 4, 5};
        int[] hasDupes = new int[] {2, 3, 3, 4};
        assertTrue("The method should return false", libraryForTest.containsDuplicates(noDupes));
        assertTrue("The method should return true", libraryForTest.containsDuplicates(hasDupes));
    }

    @Test public void testAveragesMethod() {
        Library libraryForTest = new Library();
        int[] arra = new int[] { 1, 2, 3, 4,};
        assertTrue("The method should return an average of the values in an array", libraryForTest.calculateAverages(arra) == 2.5);
    }

    @Test public void testArraysOfArraysMethod() {
        Library libraryForTest = new Library();
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60}, //63
                {57, 65, 65, 70, 72, 65, 51}, //63.57
                {55, 54, 60, 53, 59, 57, 61}, // 57
                {65, 56, 55, 52, 55, 62, 57}  // 57.4
        };
        int[] expected = new int[] {55, 54, 60, 53, 59, 57, 61};

        assertArrayEquals("The method should return the array with the lowest average", libraryForTest.arraysOfArrays(weeklyMonthTemperatures), expected);
    }
}
