/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

public class Library {
    public static int[] roll(int num){
        int [] rollArray = new int[num];
        for(int i = 0; i < num; i++){
            rollArray[i] = (int) (Math.random() * 6.0);
        }
        return rollArray;
    }

    public static boolean containsDuplicates(int[] arr){
        boolean isContained = false;

        int previousVal = arr[0];

        for(int i = 1; i < arr.length; i++){
            if(previousVal == arr[i]) {
                isContained = true;
            }
            previousVal = arr[i];
        }
        return isContained;
    }

    public static float calculateAverages(int[] arr){
        float avg = 0;
        for(int i =0; i< arr.length; i++){
            avg += arr[i];
        }
        avg = avg / arr.length;
        return avg;
    }

    public static int grabMinimum(float[] arr){
        float lowest = arr[0];
        int lowestIndex =0;
        for(int i =0; i< arr.length; i++){
            if(arr[i] < lowest){
                lowest = arr[i];
                lowestIndex = i;
            }
        }

        return lowestIndex;
    }


    public static int[] lowestAverageOfArrays(int[][] arr){
        float[] averages = new float[arr.length];
        for(int i = 0; i<arr.length; i++) {
            averages[i] = calculateAverages(arr[i]);
        }
        int idx = grabMinimum(averages);

        return arr[idx];
    }


}
